grade students now copies temporary directory to results directory

diff --git a/CSCI1200/bin/grade_students b/CSCI1200/bin/grade_students
--- a/CSCI1200/bin/grade_students
+++ b/CSCI1200/bin/grade_students
@@ -8,10 +8,12 @@ cp test.txt to_be_compiled.txt
 # END TEMPORARY
 
 echo "Temporary directory set to $2"
-
-echo "Looking for to_be_compiled.txt in $1"
+echo "Results directory set to $3"
 
 tmp="$2"
+results_path="$3"
+
+echo "Looking for to_be_compiled.txt in $1"
 
 if [[ ! -f  "$1/to_be_compiled.txt" ]]; then
 	echo "Nothing to be compiled"
@@ -24,13 +26,23 @@ while read path; do
 
 	echo "Copying path ($path) to tmp directory ($tmp/submission)"
 
-	cp -r "$path" "$tmp/submission" || echo "Failed to copy to temporary directory"
+	cp -r "$path" "$tmp/submission" || echo "ERROR: Failed to copy to temporary directory"
 
+	# RUN RUNNER
 
+	# RUN VALIDATOR
+
+	# Make directory structure in results if it doesn't exist
+
+	mkdir -p "$results_path/$path" || "ERROR: Could not create results path"
+
+	echo "Copying temporary directory to results directory"
+
+	cp -r "$tmp/submission" "$results_path/$path" || echo "ERROR: Could not copy temporary directory to results directory"
 
 	echo "Removing temporary directory ($tmp/submission)"
 
-	rm -r "$tmp/submission" || echo "Failed to remove temporary directory"
+	rm -r "$tmp/submission" || echo "ERROR: Failed to remove temporary directory"
 
 done < "$1/to_be_compiled.txt"
 
