finish PR

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -613,22 +613,17 @@ jobs:
         with:
           path: PR
 
-      - name: Compare file size
+      - name: Compare the Number of Routes
         run: |
           DIRECTORY="site/app/controllers"
-          MAIN_FILE="MAIN/$FILEPATH"
-          PR_FILE="PR/$FILEPATH"
-
-          ROUTE_NUMBER_DIFF=$(($(grep -ro "#\[Route" --include="*.php" "MAIN/$DIRECTORY" | wc -l) - $(grep -ro "#\[Route" --include="*.php" "PR/$DIRECTORY" | wc -l)))
-          echo $(grep -ro "#\[Route" --include="*.php" "MAIN/$DIRECTORY" | wc -l)
-          echo "$ROUTE_NUMBER_DIFF"
-          if [ $ROUTE_NUMBER_DIFF -gt 0 ]; then
-            echo "::error::colors.css has increased in size by $LINES_DIFF lines in this PR."
-            echo "::error::Please use existing colors in colors.css instead of adding new ones, to keep the size of the file manageable."
-            echo "::error::If adding to colors.css really is necessary for your PR, this requirement may be waived on maintainer review."
-            exit $LINES_DIFF
+          ROUTE_NUMBER_DIFF=$(( $(grep -ro "#\[Route" --include="*.php" "MAIN/$DIRECTORY" | wc -l) - $(grep -ro "#\[Route" --include="*.php" "PR/$DIRECTORY" | wc -l) ))
+          if [ $ROUTE_NUMBER_DIFF -ne 0 ]; then
+            echo "::error::The number of routes has changed by $ROUTE_NUMBER_DIFF in this PR."
+            echo "::error::Please make sure that routes do not conflict with each other."
+            echo "::error::This requirement may be waived on maintainer review after thorough checking."
+            exit 1
           else
-            echo "No lines added. OK."
+            echo "No Routes added. OK."
           fi
 
 
