Reverted Changes and changed dumper

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,9 +7,6 @@ on:
   pull_request:
   workflow_dispatch:
 
-permissions:
-  contents: read
-
 env:
   PGPASSWORD: submitty_dbuser
   PHP_USER: submitty_php
@@ -19,7 +16,7 @@ env:
   SUBMITTY_INSTALL_DIR: /usr/local/submitty
   SUBMITTY_REPOSITORY: /usr/local/submitty/GIT_CHECKOUT/Submitty
   POSTGRES_HOST: localhost
-  PHP_VER: 8.2
+  PHP_VER: 8.1
   NODE_VERSION: 20
   PYTHON_VERSION: "3.10"
 
@@ -621,30 +618,24 @@ jobs:
       - name: Compare Migrated master Database with Provided Dump
         if: always()
         run: |
-          diff --color \
-            -I '^\\\\restrict' \
-            -I '^\\\\unrestrict' \
-            ${GITHUB_WORKSPACE}/dumped/branch/master.sql \
-            ${PR_REPO_PATH}/Submitty/migration/migrator/data/submitty_db.sql \
-            || { echo "::error:: Wrong provided dump, please check your database dumps"
+          diff --color ${GITHUB_WORKSPACE}/dumped/branch/master.sql                         \
+                       ${PR_REPO_PATH}/Submitty/migration/migrator/data/submitty_db.sql || {
+            echo "::error:: Wrong provided dump, please check your database dumps"
             exit 1
           }
 
       - name: Compare Migrated course Database with Provided Dump
         if: always()
         run: |
-          diff --color \
-            -I '^\\\\restrict' \
-            -I '^\\\\unrestrict' \
-            ${GITHUB_WORKSPACE}/dumped/branch/course.sql \
-            ${PR_REPO_PATH}/Submitty/migration/migrator/data/course_tables.sql \ 
-            || { echo "::error:: Wrong provided dump, please check your database dumps"
+          diff --color ${GITHUB_WORKSPACE}/dumped/branch/course.sql                         \
+                       ${PR_REPO_PATH}/Submitty/migration/migrator/data/course_tables.sql || {
+            echo "::error:: Wrong provided dump, please check your database dumps"
             exit 1
           }
 
       - name: Pack Artifacts
         if: failure()
-        uses: actions/upload-artifact@v7
+        uses: actions/upload-artifact@v6
         with:
           name: dumped_database
           path: ${{ github.WORKSPACE }}/dumped/**/*.sql
@@ -810,19 +801,19 @@ jobs:
           http_ver=$(curl -ksI https://localhost -o/dev/null -w "%{http_version}\n")
           [ "$http_ver" = "2" ] && echo "Pass" || echo "::warning::Failed"
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Submitty-JSON
           path: /usr/local/submitty/config/submitty.json
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Cypress-System-Screenshots
           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Cypress-System-Videos
@@ -900,12 +891,12 @@ jobs:
         working-directory: ${{ env.SUBMITTY_REPOSITORY }}
         run: sudo bash tests/test_site_error_log.sh
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Cypress-${{matrix.containers}}-Screenshots
           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Cypress-${{matrix.containers}}-Videos
@@ -1003,19 +994,19 @@ jobs:
           working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
           browser: chrome
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: install-log
           path: /usr/local/submitty/install.log
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Cypress-Ansible-Screenshots
           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
 
-      - uses: actions/upload-artifact@v7
+      - uses: actions/upload-artifact@v6
         if: failure()
         with:
           name: Cypress-Ansible-Videos
