actually add the things

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -597,6 +597,40 @@ jobs:
           path: ${{ github.WORKSPACE }}/dumped/**/*.sql
           retention-days: 3
 
+  routes:
+    name: Route Check
+    runs-on: ubuntu-22.04
+
+    steps:
+      - name: Checkout main branch
+        uses: actions/checkout@v4
+        with:
+          ref: main
+          path: MAIN
+
+      - name: Checkout PR branch
+        uses: actions/checkout@v4
+        with:
+          path: PR
+
+      - name: Compare file size
+        run: |
+          DIRECTORY="site/app/controllers"
+          MAIN_FILE="MAIN/$FILEPATH"
+          PR_FILE="PR/$FILEPATH"
+
+          ROUTE_NUMBER_DIFF=$(((grep -ro "#\[Route" --include="*.php" "MAIN/$DIRECTORY" | wc -l) - $(grep -ro "#\[Route" --include="*.php" "PR/$DIRECTORY" | wc -l)))
+          echo $(grep -ro "#\[Route" --include="*.php" "MAIN/$DIRECTORY" | wc -l)
+          echo "$ROUTE_NUMBER_DIFF"
+          if [ $LINES_DIFF -gt 0 ]; then
+            echo "::error::colors.css has increased in size by $LINES_DIFF lines in this PR."
+            echo "::error::Please use existing colors in colors.css instead of adding new ones, to keep the size of the file manageable."
+            echo "::error::If adding to colors.css really is necessary for your PR, this requirement may be waived on maintainer review."
+            exit $LINES_DIFF
+          else
+            echo "No lines added. OK."
+          fi
+
 
   Cypress-System:
     name: Cypress (System)
