echo PR name

diff --git a/.github/workflows/submitty_ci.yml b/.github/workflows/submitty_ci.yml
--- a/.github/workflows/submitty_ci.yml
+++ b/.github/workflows/submitty_ci.yml
@@ -374,168 +374,168 @@ jobs:
 #           working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
 #           browser: chrome
 
-      - name: Switch to database auth
-        run: sudo sed -ie "s/Pam/Database/g" ${SUBMITTY_INSTALL_DIR}/config/authentication.json
+#       - name: Switch to database auth
+#         run: sudo sed -ie "s/Pam/Database/g" ${SUBMITTY_INSTALL_DIR}/config/authentication.json
 
-      - name: Run cypress e2e login tests with database auth
-        uses: cypress-io/github-action@v6
-        with:
-          config: baseUrl=http://localhost
-          spec: cypress/e2e/Cypress-System/login.spec.js
-          working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
-          browser: chrome
+#       - name: Run cypress e2e login tests with database auth
+#         uses: cypress-io/github-action@v6
+#         with:
+#           config: baseUrl=http://localhost
+#           spec: cypress/e2e/Cypress-System/login.spec.js
+#           working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
+#           browser: chrome
 
-      - name: Switch to LDAP auth
-        run: sudo sed -ie "s/Database/Ldap/g" ${SUBMITTY_INSTALL_DIR}/config/authentication.json
+#       - name: Switch to LDAP auth
+#         run: sudo sed -ie "s/Database/Ldap/g" ${SUBMITTY_INSTALL_DIR}/config/authentication.json
 
-      - name: Run cypress e2e login tests with LDAP auth
-        uses: cypress-io/github-action@v6
-        with:
-          config: baseUrl=http://localhost
-          spec: cypress/e2e/Cypress-System/login.spec.js
-          working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
-          browser: chrome
+#       - name: Run cypress e2e login tests with LDAP auth
+#         uses: cypress-io/github-action@v6
+#         with:
+#           config: baseUrl=http://localhost
+#           spec: cypress/e2e/Cypress-System/login.spec.js
+#           working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
+#           browser: chrome
 
-      - name: Setup SAML
-        run: |
-          cd $SUBMITTY_REPOSITORY
-          sudo -E env "PATH=$PATH" bash .setup/testing/setup_saml.sh
+#       - name: Setup SAML
+#         run: |
+#           cd $SUBMITTY_REPOSITORY
+#           sudo -E env "PATH=$PATH" bash .setup/testing/setup_saml.sh
 
-      - name: Switch to SAML auth
-        run: sudo sed -ie "s/Ldap/Saml/g" ${SUBMITTY_INSTALL_DIR}/config/authentication.json
+#       - name: Switch to SAML auth
+#         run: sudo sed -ie "s/Ldap/Saml/g" ${SUBMITTY_INSTALL_DIR}/config/authentication.json
 
-      - name: Run cypress e2e login tests with SAML auth
-        uses: cypress-io/github-action@v6
-        with:
-          config: baseUrl=http://localhost,chromeWebSecurity=false
-          spec: cypress/e2e/Cypress-System/login.spec.js
-          working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
-          browser: chrome
+#       - name: Run cypress e2e login tests with SAML auth
+#         uses: cypress-io/github-action@v6
+#         with:
+#           config: baseUrl=http://localhost,chromeWebSecurity=false
+#           spec: cypress/e2e/Cypress-System/login.spec.js
+#           working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
+#           browser: chrome
 
-      - name: Setup HTTP/2
-        run: |
-          cd $SUBMITTY_REPOSITORY
-          if [ -f .setup/dev-upgrade-h2.sh ]; then
-            sudo sed -e "s/:80/:443/g" --in-place /etc/apache2/sites-available/submitty.conf
-            sudo -E env "PATH=$PATH" bash .setup/dev-upgrade-h2.sh up --i-know-what-i-am-doing-please-go-ahead \
-              && echo "Setup OK"  \
-              || {
-                echo "::warning::Setup Failed"
-                sudo sed -e "s/:443/:80/g" --in-place /etc/apache2/sites-available/submitty.conf
-              }
-          else
-            echo "Could not find dev-upgrade-h2.sh, skipping"
-          fi
+#       - name: Setup HTTP/2
+#         run: |
+#           cd $SUBMITTY_REPOSITORY
+#           if [ -f .setup/dev-upgrade-h2.sh ]; then
+#             sudo sed -e "s/:80/:443/g" --in-place /etc/apache2/sites-available/submitty.conf
+#             sudo -E env "PATH=$PATH" bash .setup/dev-upgrade-h2.sh up --i-know-what-i-am-doing-please-go-ahead \
+#               && echo "Setup OK"  \
+#               || {
+#                 echo "::warning::Setup Failed"
+#                 sudo sed -e "s/:443/:80/g" --in-place /etc/apache2/sites-available/submitty.conf
+#               }
+#           else
+#             echo "Could not find dev-upgrade-h2.sh, skipping"
+#           fi
 
-      - name: Test HTTP/2 Connection
-        run: |
-          http_ver=$(curl -ksI https://localhost -o/dev/null -w "%{http_version}\n")
-          [ "$http_ver" = "2" ] && echo "Pass" || echo "::warning::Failed"
-
-
-      - uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: cypress-screenshots
-          path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
-      - uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: cypress-videos
-          path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/videos
-
-      - name: Check for site errors
-        working-directory: ${{ env.SUBMITTY_REPOSITORY }}
-        run: sudo bash tests/test_site_error_log.sh
-
-  Cypress:
-    runs-on: ubuntu-22.04
-    strategy:
-      fail-fast: false
-      matrix:
-        containers: ["Gradeable", "Admin", "UI", "Feature"]
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: submitty_dbuser
-          POSTGRES_USER: postgres
-          TZ: America/New_York
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/e2e-Setup-Composite
-      # TODO: Remove this block after upgrading jsPDF
-      - name: Cache Node Modules
-        uses: actions/cache@v4
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-cache-node-modules-dev-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-              ${{ runner.os }}-cache-node-modules-dev
-
-      - name: Install node dependencies
-        working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
-        run: |
-          npm install file-saver --save
-          npm install --production=false
-
-      - name: Run cypress e2e tests with pam auth
-        uses: cypress-io/github-action@v6
-        with:
-          config: baseUrl=http://localhost
-          working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
-          spec: cypress/e2e/Cypress-${{matrix.containers}}/*
-          browser: chrome
-          env: run_area=CI
-
-      - name: Check for site errors
-        working-directory: ${{ env.SUBMITTY_REPOSITORY }}
-        run: sudo bash tests/test_site_error_log.sh
-
-      - uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: cypress-screenshots
-          path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
-      - uses: actions/upload-artifact@v4
-        if: failure()
-        with:
-          name: cypress-videos
-          path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/videos
+#       - name: Test HTTP/2 Connection
+#         run: |
+#           http_ver=$(curl -ksI https://localhost -o/dev/null -w "%{http_version}\n")
+#           [ "$http_ver" = "2" ] && echo "Pass" || echo "::warning::Failed"
 
 
-  Integration:
-    runs-on: ubuntu-22.04
-    # Postgres should not be needed for the integration tests.
-    # But unfortunately Configure test suite seems to use it at the moment, and
-    # Configure test suite seems to be necessary for the Integration tests
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: submitty_dbuser
-          POSTGRES_USER: postgres
-          TZ: America/New_York
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
+#       - uses: actions/upload-artifact@v4
+#         if: failure()
+#         with:
+#           name: cypress-screenshots
+#           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
+#       - uses: actions/upload-artifact@v4
+#         if: failure()
+#         with:
+#           name: cypress-videos
+#           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/videos
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - uses: ./.github/actions/e2e-Setup-Composite
-      - name: Run integration tests
-        run: sudo -E env "PATH=$PATH" python3 /usr/local/submitty/test_suite/integrationTests/run.py
+#       - name: Check for site errors
+#         working-directory: ${{ env.SUBMITTY_REPOSITORY }}
+#         run: sudo bash tests/test_site_error_log.sh
+
+#   Cypress:
+#     runs-on: ubuntu-22.04
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         containers: ["Gradeable", "Admin", "UI", "Feature"]
+#     services:
+#       postgres:
+#         image: postgres
+#         env:
+#           POSTGRES_PASSWORD: submitty_dbuser
+#           POSTGRES_USER: postgres
+#           TZ: America/New_York
+#         options: >-
+#           --health-cmd pg_isready
+#           --health-interval 10s
+#           --health-timeout 5s
+#           --health-retries 5
+#         ports:
+#           - 5432:5432
+
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
+#       - uses: ./.github/actions/e2e-Setup-Composite
+#       # TODO: Remove this block after upgrading jsPDF
+#       - name: Cache Node Modules
+#         uses: actions/cache@v4
+#         with:
+#           path: ~/.npm
+#           key: ${{ runner.os }}-cache-node-modules-dev-${{ hashFiles('**/package-lock.json') }}
+#           restore-keys: |
+#               ${{ runner.os }}-cache-node-modules-dev
+
+#       - name: Install node dependencies
+#         working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
+#         run: |
+#           npm install file-saver --save
+#           npm install --production=false
+
+#       - name: Run cypress e2e tests with pam auth
+#         uses: cypress-io/github-action@v6
+#         with:
+#           config: baseUrl=http://localhost
+#           working-directory: ${{env.SUBMITTY_REPOSITORY}}/site
+#           spec: cypress/e2e/Cypress-${{matrix.containers}}/*
+#           browser: chrome
+#           env: run_area=CI
+
+#       - name: Check for site errors
+#         working-directory: ${{ env.SUBMITTY_REPOSITORY }}
+#         run: sudo bash tests/test_site_error_log.sh
+
+#       - uses: actions/upload-artifact@v4
+#         if: failure()
+#         with:
+#           name: cypress-screenshots
+#           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/screenshots
+#       - uses: actions/upload-artifact@v4
+#         if: failure()
+#         with:
+#           name: cypress-videos
+#           path: ${{env.SUBMITTY_REPOSITORY}}/site/cypress/videos
+
+
+#   Integration:
+#     runs-on: ubuntu-22.04
+#     # Postgres should not be needed for the integration tests.
+#     # But unfortunately Configure test suite seems to use it at the moment, and
+#     # Configure test suite seems to be necessary for the Integration tests
+#     services:
+#       postgres:
+#         image: postgres
+#         env:
+#           POSTGRES_PASSWORD: submitty_dbuser
+#           POSTGRES_USER: postgres
+#           TZ: America/New_York
+#         options: >-
+#           --health-cmd pg_isready
+#           --health-interval 10s
+#           --health-timeout 5s
+#           --health-retries 5
+#         ports:
+#           - 5432:5432
+
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
+#       - uses: ./.github/actions/e2e-Setup-Composite
+#       - name: Run integration tests
+#         run: sudo -E env "PATH=$PATH" python3 /usr/local/submitty/test_suite/integrationTests/run.py
